name: offlineimap
version: '7.1.5'
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local 
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.

grade: stable
confinement: strict

apps:
  offlineimap:
    command: bin/offlineimap
    plugs:
      - network

parts:
  setup:
    plugin: python
    python-version: python2
    python-packages: [six]
  offlineimap:
    after: [setup]
    plugin: python
    python-version: python2
    source: https://github.com/OfflineIMAP/offlineimap.git
    source-tag: 'v7.1.5'
