name: offlineimap
version: 'master'
summary: OfflineIMAP
description: |
  Read/sync your IMAP mailboxes

grade: stable
confinement: strict

apps:
  offlineimap:
    command: bin/offlineimap
    plugs:
      - network

parts:
  setup:
    plugin: python
    python-version: python2
    python-packages: [six]
  offlineimap:
    after: [setup]
    plugin: python
    python-version: python2
    source: https://github.com/OfflineIMAP/offlineimap.git
