name: offlineimap
version: stable
version-script: git -C parts/offlineimap/build describe --tags
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local 
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.

grade: stable
confinement: strict

apps:
  offlineimap:
    command: bin/offlineimap
    plugs:
      - network
      - home
      - removable-media

parts:
  setup:
    plugin: python
    python-version: python2
    python-packages: [six]
  offlineimap:
    after: [setup]
    plugin: python
    python-version: python2
    source: https://github.com/OfflineIMAP/offlineimap.git
    prepare: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info offlineimap | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
